### ISSUE TITLE
Cannot run the script

### ISSUE THREAD

**Issue by AresS31** [lmammino/jwt-cracker#1]
Hi,

I followed the instructions on "how to run the script" but cannot get it work.

Here is the stack trace:
```
/usr/local/lib/node_modules/jwt-cracker/index.js:49
const [header, payload, signature] = token.split('.');
      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

**Comment by lmammino** [comment]
Hello @AresS31,
I think you are using a version of node that doesn't support destructing (new es2015 feature).

If you update to node >= 6.0.0 that should be enough to make the script work.

**Comment by AresS31** [comment]
That was the issue I was using the **version 4.6.1** of NodeJs.

Thanks.

**Comment by lmammino** [comment]
No prob.
Thanks to you for trying it out and spotting this issue. I will see how can i make clear what's the minimum required node version in the readme and the package.json, so I will re open this for now until this is done.
