### ISSUE TITLE
test

### ISSUE THREAD

**Issue by mohmdmed9** [lmammino/jwt-cracker#15]

**Comment by lmammino** [comment]
Hello @mohmdmed9 and thanks for reaching out.

The command looks ok.

How long did you wait?

Did you try to narrow down the alphabet (since you know the secret) just to validate if the secret is found (faster) that way?

**Comment by mohmdmed9** [comment]
Thanks for the quick response @lmammino 
I'm still waiting, is the command ok eventhough I did not specify the exsisting of a special charchter?
I will try to narrow down the alphabet

**Comment by mohmdmed9** [comment]
I'm still waiting, is the command ok? even though I did not specify the existence of a special character? I will try to narrow down the alphabet

**Comment by lmammino** [comment]
Hey @mohmdmed9, did you figure out what was the issue?

**Comment by mohmdmed9** [comment]
Hi @lmammino I did find a solution with Hashcat but not with jwt-cracker

**Comment by lmammino** [comment]
Would you be willing to share the details of the token you were trying to crack? I think it could be helpful to compare the results!

**Comment by mohmdmed9** [comment]
I just want to verify if the secret key of my app can be crackable with a fastest method. 
The secret key of my app is tHe$2020 (Just an app for training purpose) 


I used the 'policygen' command from the PACK toolkit to generate all masks that conform to the complexity requirements, 
I wrote all of those masks in a file :
python policygen.py --minlength 8 --maxlength 8 --minlower 2 --minupper 1 --mindigit 4 --minspecial 1 -o jwt.hcmask  

And then pass it to hashcat, but, Hashcat could not find the secret key and I still don't know why.
