### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by itsrvsingh** [lmammino/jwt-cracker#17]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jwt-crackerp - Not found
npm ERR! 404 
npm ERR! 404  'jwt-crackerp@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-03T15_53_29_869Z-debug.log

**Comment by itsrvsingh** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jwt-craker - Not
found
npm ERR! 404
npm ERR! 404  ***@***.***' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name
yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hack3r/.npm/_logs/2022-02-03T16_08_55_414Z-debug.log

**Comment by lmammino** [comment]
![Screenshot 2022-02-03 at 16 11 45](https://user-images.githubusercontent.com/205629/152381773-178d5cd5-5bd8-4f77-846f-c320ca03e02e.png)

Just tested it and it runs for me. Are you behind some proxy?

**Comment by itsrvsingh** [comment]
ok thanks now its work properly
