### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Os3r3um** [lmammino/jwt-cracker#3]
Hi, 

I ran into this issue testing this cracker with the default jwt token. 

```
ubuntu:~/Desktop/api_testing/jwt-cracker$ jwt-cracker "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ" "abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789" 6
/usr/local/lib/node_modules/jwt-cracker/index.js:49
const [header, payload, signature] = token.split('.');
      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

System: uname -a
Linux ubuntu 4.8.0-56-generic #61-Ubuntu SMP Wed Jun 14 08:15:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
npm -v -> 3.5.2

node -v -> 4.2.6

Any ideas how to fix it?

Cheers.

**Comment by lmammino** [comment]
Hello @Os3r3um,
Thanks for submitting this issue.

The code here is expected to be executed in node >= 6 (due to the adoption of some es2015 syntactic sugars).

Try with updating your version of node and feel free to reopen the issue if you still have similar problems.

**Comment by Os3r3um** [comment]
Hi, Thanks. I got the point. Will try install node > 6 and give it a try. Thanks for your time looking into this. :)

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>MRHV68

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>bKPDr5

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>WZmBEl

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>uhMA0I

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>2xUNGr

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1HO0ph

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>AD85AE

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ksJcEZ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tOMz47

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Q2k7RK

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Ui6QNw

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lCCB3i

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>2vgdwS

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oMWlqb

**Comment by Dody2004Sec** [comment]
'"><div rNnTRbt=roann>tS2wxH

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>PfPo15

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>wBYdbZ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>emHlzG

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>vqkvlP

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>AXIO08

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>vgS7hF

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>NzzTMS

**Comment by Dody2004Sec** [comment]
'" rNnTRbt="roannATTR" x=y1uFyum

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>0ETygn

**Comment by Dody2004Sec** [comment]
'"></script><div rNnTRbt=roann>lw8b7t

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>bIyuJl

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>fxSCJN

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>LgkL6J

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>vnjw1u

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>sCozEF

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tJXx7d

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>YOjCwo

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>A1K2yR

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>8t3Ux0

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>JYO3xk

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>kRbakX

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>nB8AKu

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>2zRt6A

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>aBldwp

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>6zUcAA

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tNtkwL

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>u8m3OU

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>CpbfDx

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>mO9cIc

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Ni0PXj

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>F6nQiC

**Comment by Dody2004Sec** [comment]
'"><div rNnTRbt=roann>mpjoe7

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ZQkjnJ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>BxzEmt

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>kR9kOu

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>SFytl4

**Comment by Dody2004Sec** [comment]
'"></script><div rNnTRbt=roann>Xl7VCO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>On9sYZ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>4Q8sDa

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>626h6A

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>zBmlm0

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>srUVk0

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>m3jcfU

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>QLNJk3

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>uuOL1z

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ziDOTC

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>VeoGbB

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>H1slfH

**Comment by Dody2004Sec** [comment]
'" rNnTRbt="roannATTR" x=y2xImDL

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>z3XzbT

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>dfG9pr

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>DXdu4Q

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>prtplK

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>TQMUOE

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>G0m5mn

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>sxRYsu

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>5NcdEQ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>bw4iR7

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>uSs3gn

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>vuLrYH

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>KiygFR

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Fl44KG

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>g9E3kj

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>TYaMfj

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>i3Zq9o

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>5uSyqq

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>kH0TOu

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lPtNRh

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Lbjx4K

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Q4MnsM

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>EseVKO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>otCgKm

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>uckEvh

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>MWv9fb

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>P6eMJD

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>IJXEyS

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>hR2xmW

**Comment by Dody2004Sec** [comment]
'" rNnTRbt="roannATTR" x=y5jn42h

**Comment by Dody2004Sec** [comment]
'"><div rNnTRbt=roann>zlWmqU

**Comment by Dody2004Sec** [comment]
'"></script><div rNnTRbt=roann>7tLGR7

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>NtNOFW

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Dq5TYD

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ASiyHk

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>g1kYbt

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ixCdG4

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Fhqefk

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>aSMv0b

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>p4o2zS

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>wrAwog

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ocZIyW

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>THYY7n

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>uESYpY

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tryBsg

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lzHiES

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tWOevJ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>T2eyjQ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>mRKTYI

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1rUfDt

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>5ZrXTT

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lIRcgQ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>6qWeZO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Xp0y7t

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>b7LB8K

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>GNdJER

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>g17eSF

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>bncgRE

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>y49yTh

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>UfyXXy

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>V2fYFQ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>LdeP2u

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Tnij3k

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>AN8izw

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>taNYow

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jPKQGs

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>pzHVqu

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>nSFS5J

**Comment by Dody2004Sec** [comment]
'" rNnTRbt="roannATTR" x=yKEerCs

**Comment by Dody2004Sec** [comment]
'"><div rNnTRbt=roann>gbaH0l

**Comment by Dody2004Sec** [comment]
'"></script><div rNnTRbt=roann>AWVGSq

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ISFEVd

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>MvT0l7

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>GsiOuZ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>nUGUzM

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>xBYJyl

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lrH1Dv

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>O0Pu3z

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>IJDQQW

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>3jndgA

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>evg7YO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lVLtb0

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>kdodsk

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>0YtYzq

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>iEjxrq

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>yoR1XF

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>kxsuEO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>huuTf0

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>baOlIb

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>dsvnNv

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ELviQc

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>r8WCXY

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Y0HiwJ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>u9lriO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>UqyQoc

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Tl2fCT

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>fSPOZT

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>0bI5JH

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>brRALU

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Xxcphp

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tQgodU

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>c7eTte

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1HzD5v

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jelnCa

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>LzFOa2

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>8IliOZ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>54uwlN

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>2J56UO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>y4DBla

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>A6Il3W

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>CNFZsx

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>pRkAvz

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>KfkUTu

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>4ywhGY

**Comment by Dody2004Sec** [comment]
'"><div rNnTRbt=roann>rvA4yc

**Comment by Dody2004Sec** [comment]
'" rNnTRbt="roannATTR" x=yDhPaCE

**Comment by Dody2004Sec** [comment]
'"></script><div rNnTRbt=roann>QaMGud

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>XyekOj

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>3euiQ9

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>YENQdn

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>IqaVov

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>NGMOzf

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>z46834

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>y29xEz

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oUf4O5

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>dL9b0C

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>galRm1

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>9drPky

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>hEV897

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>DxIpKG

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>RvcBC7

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Qo4Pd4

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>2Eoqm0

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>o1uw7V

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Dindbv

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Y1EjKi

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>XjptP4

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>2blqNH

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Cv3Czs

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>E5NrRv

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>XkpHA6

**Comment by Dody2004Sec** [comment]
tets

**Comment by Dody2004Sec** [comment]
tets

**Comment by Dody2004Sec** [comment]
tets

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ASjcGq

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>KDHTkG

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>hMdlc2

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jld7FR

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ljdIjf

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>T1ewSx

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jUYT0l

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>SYV6w9

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Gv5xIT

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Dpi3dS

**Comment by Dody2004Sec** [comment]
'"><div rNnTRbt=roann>nt7aaf

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>QeHnBL

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>DAI3Nq

**Comment by Dody2004Sec** [comment]
'"></script><div rNnTRbt=roann>2d0DJL

**Comment by Dody2004Sec** [comment]
'" rNnTRbt="roannATTR" x=y6GdmTW

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>rzgIUE

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>L62eo6

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>pscDNO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>n5GX1x

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>BaNEXO

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>CLRXiz

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>f37Gu5

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>MqJJl5

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>ULtGKb

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>A6vk7m

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>8YfCmq

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>OZYLee

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>xVuCMQ

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>KBm4Rc

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>GQS00V

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>4PllZs

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>3ZEw8e

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>68SrCh

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>sb7qGm

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>inGiK5

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>TN84oA

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Jua0up

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>XuOt9v

**Comment by Dody2004Sec** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>JBB9Jt
