### ISSUE TITLE
It doesn't work if the dash is included in the alphabet

### ISSUE THREAD

**Issue by h4ppyy** [lmammino/jwt-cracker#9]
It doesn't work if the dash is included in the alphabet
I created the secret key as 'abc-'
But I couldn't find the secret key

jwt-cracker "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjkzaW1tbSIsInN5c3RlbSI6ImZyb250IiwiaWF0IjoxNTY0NTYwNjAwfQ.2ln1F_uMKeAFtEkFC-RL6nAzwQH5p_3q5ufy7GylndU" "abc-" 4

**Comment by lmammino** [comment]
hello @h4ppyy, thanks for reporting this. Would you like to submit a PR for fixing this issue?
